version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: conhece-recife
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'conhece-recife'
    ports:
      - '3316:3306'
